### ISSUE TITLE
Can you create a README describing the relationship of this code-base to the SourceForge projects?

### ISSUE THREAD

**Issue by dbolser** [samtools/tabix#1]
It's confusing for people who aren't intimately familiar with the project. i.e. is the code here packaged for download via SF? Is the SF project now obsolete? Why is there a separate tabix / bzip SF projects? etc.

Cheers,
Dan.

**Comment by daviesrob** [comment]
This has now been done, and it's more obvious that the SourceForge repository is obsolete.

I've added a [commit](https://sourceforge.net/p/samtools/code/1013/tree/trunk/tabix/) on SourceForge that replaces the tabix code with a README file pointing at [HTSlib](https://github.com/samtools/htslib).  This is essentially a copy of a similar commit that did the same thing for samtools.  I've also put a README.txt file in the [tabix releases directory](https://sourceforge.net/projects/samtools/files/tabix/) which is a slight rewording of the [README.md](https://github.com/samtools/tabix/blob/master/README.md) file added here by #31.

Hopefully these will help redirect people to HTSlib as the place to find tabix.
