### ISSUE TITLE
error indexing gff3 file

### ISSUE THREAD

**Issue by thierryjanssens** [samtools/tabix#26]
What does the following error mean?

It is a merged and sorted gff3 file, containing SPADES scaffolds names.

[get_intv] the following line cannot be parsed and skipped: >NODE_1000_length_470_cov_0.860058
[ti_index_core] the indexes overlap or are out of bounds

**Comment by valeriuo** [comment]
This repo is not actively maintained. Try using the _tabix_ that comes with [HTSlib](https://github.com/samtools/htslib/releases).
