### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by alefnula** [samtools/tabix#7]
Hi,

I looked at the code and I saw that `tabix` supports fetching files from `http` and `ftp`, but there is no `https` support. Is something like this even on the roadmap, or it's completely out of the scope.

Best,
Viktor

**Comment by jmarshall** [comment]
Tabix development moved to being bundled with [htslib](https://github.com/samtools/htslib) some years ago, and since version 1.3 HTSlib and `tabix` have supported https (by using libcurl).
